### ISSUE TITLE
No video in YouTube app when clicking the cardboard icon

### ISSUE THREAD

**Issue by superruzafa** [Kjos/JitteryGyroFixForCardboard#6]
When the module is enabled, any 360º video in the YouTube app in fullscreen (landscape) and in cardboard mode shows no video, only the vertical bar and the gear icon.

Tested in a Motorola Moto G (2014)

**Comment by Kjos** [comment]
Thanks for posting the bug. Do you use Lollipop?

**Comment by superruzafa** [comment]
Yes.
BTW, the gyroscope works and is stable in the Google Cardboard Camera app.

**Comment by Kjos** [comment]
Can you point me to the xposed installer you used? I haven't tried on
Lollipop yet, because for a long while motog was unsupported. I might give
it a try tomorrow then.

**Comment by superruzafa** [comment]
Sure!
[xposed-v79-sdk22-arm.zip](http://forum.xda-developers.com/attachment.php?attachmentid=3580244&d=1450386592)

**Comment by Kjos** [comment]
Fixed this. I'll ask lrq3000 to update the Xposed module, as he is in charge of that. Meanwhile you can get the new APK from my dropbox: https://www.dropbox.com/s/kqgy74p6b3slvch/GyroscopeNoiseFilter.apk?dl=0 .

**Comment by superruzafa** [comment]
It works perfectly, thanks!

**Comment by lrq3000** [comment]
Wow amazing Kjos! Yes I'll update by this evening :)

2016-01-10 12:30 GMT+01:00 Alfonso Ruzafa notifications@github.com:

**Comment by Kjos** [comment]
No problem :) Have fun!

2016-01-10 13:03 GMT+01:00 Stephen L. notifications@github.com:

**Comment by lrq3000** [comment]
Hey Kjos, could you please change the version and compile an APK? I don't have an Android compiler on my current computer...

**Comment by lrq3000** [comment]
Ah and also add to the CHANGELOG.md:
- 1.6:
  - fixed youtube not playing videos when module activated.

2016-01-10 13:14 GMT+01:00 Kjos notifications@github.com:

**Comment by Kjos** [comment]
You should be able to download the apk from this link, lrq3000: https://www.dropbox.com/s/kqgy74p6b3slvch/GyroscopeNoiseFilter.apk?dl=0 

I updated the manifest and change log.

Cheers!

**Comment by lrq3000** [comment]
Ok done, thank's Kjos :)

2016-01-10 21:03 GMT+01:00 Kjos notifications@github.com:

**Comment by Kjos** [comment]
Thank YOU for uploading to the xposed repo :)
