### ISSUE TITLE
Cardboard Camera screen jittering in 1.6

### ISSUE THREAD

**Issue by superruzafa** [Kjos/JitteryGyroFixForCardboard#7]
After fixing #6 the video is shown (and without jittering) in the Youtube app but now the screen is jittering in the Cardboard Camera app, Google Street View app... It seems like the module was disabled, but it is enabled.

Xposed Framework: v79 sdk22 arm
XposedJitteryGyroFix 1.6
Lollipop 5.1
Motorola Moto G 2014

**Comment by Kjos** [comment]
But it did correctly work before with filtering?

**Comment by superruzafa** [comment]
Tested several times:
With v1.5 screen was stable in those apps but without Youtube video.
With v1.6 Youtube video is working and it's stable but the rest of apps have a shaky screen.
Exactly the same default settings for both versions.

**Comment by Kjos** [comment]
Can you try with double of the previous settings? So median filter of 10 becomes 20, LP filter of 0.2 becomes 0.1 etc? 
Previously the filter was applied twice, unknowingly.

**Comment by superruzafa** [comment]
I changed the only non default/disabled value (filter size) for the median filter type to 10, 20, 100...
In v1.6 changing the settings don't seem to have effect.
In v1.5 changes are applied immediately, showing a smooth transition in the screens.

**Comment by Kjos** [comment]
In what apps have you tested setting the filter to a higher value? Is this the Carboard Camera? It seems then that the hook that I redacted might have worked on the Camera app. Maybe I can add a switch to enable the different hook.

**Comment by Kjos** [comment]
Because it seems to work for me, but I'm currently only testing with a rollercoaster app.

The village for Google Cardboard app works too.

It doesn't work in Cardboard Camera for me neither, I'll look into it.

**Comment by Kjos** [comment]
Updated APK: https://www.dropbox.com/s/kqgy74p6b3slvch/GyroscopeNoiseFilter.apk?dl=0

Now has a hookswitch; you need to close the entire app before the hook switch will work.

The first hook and the last one are the ones you want to use.

**Comment by lrq3000** [comment]
Ok thank's Kjos. Alfonso, can you confirm that it works with the new APK in
all apps, including Youtube, by playing the hooktypes in the options?

2016-01-12 0:04 GMT+01:00 Kjos notifications@github.com:

**Comment by Kjos** [comment]
I tested with the Youtube app (hook 1) and Cardboard Camera (hook 3). I'm not sure hook 2 has any real purpose, it's been a while since I've used that. I also changed the filter to ignore NaN values, as this can mess up the LP filter at the least. Also I changed the filter array size from 13 to 16; although it might work with 13 I set it to 16 to represent the 4x4 matrix it is filtering (if I'm not mistaken and IIRC that is the case).

**Comment by Kjos** [comment]
I got a quick question: how much ruckus would it make if I added positional tracking to Cardboard with Xposed?

**Comment by lrq3000** [comment]
It would be quite a lot of work because I think that you would need to
reimplement the functions to manage position (or you'd have to include
Cardboard lib in your project, not sure if that would work since it's a
linked binary, IIRC I could not), but as long as you have access to the
sensor's positions, you can do anything you want, so that's possible I
think (for most apps at least).

2016-01-12 0:38 GMT+01:00 Kjos notifications@github.com:

**Comment by Kjos** [comment]
Mmm... the Cardboard application wouldn't be able to use the translation itself, but you would be able to move into the scene. There might be some weird frustum culling occurring though although that's mostly based by rotation anyway so maybe not..
I would just replace the translation values in the getEyeView params, so it would work with every app. I think it could be done pretty quickly, so might be worth a shot. But would it gain attention?

**Comment by Kjos** [comment]
Actually the Cardboard application could get the translation (it's late).. Although no applications are written that actively use the translation.

**Comment by Kjos** [comment]
Did just now a quick test setting the translation values. It works :)

**Comment by superruzafa** [comment]
Here are my results:

| Hook type/App | Cardboard Camera | Google Street View | Youtube | VR Roller coaster |
| --- | --- | --- | --- | --- |
| Most compatible hook | ✗ | ✗ | ✓ | ✓ |
| Cardboard hook 1 | ✗ | ✗ | ✗ (jittering) | ✓ |
| Cardboard hook 2 | ✓ | ✗ | ✗ (no video) | ✗ |

Thanks!
